### PR TITLE
Fix #34.

### LINKED ISSUE #34: test.ts(326,13): error TS2554: Expected 1 arguments, but got 0.
Same thing here now (with ngimport 0.7.2)

```

> ngcomponent@3.0.1 pretest /home/tlv/dev/ngcomponent
> npm run build


> ngcomponent@3.0.1 build /home/tlv/dev/ngcomponent
> npm run clean && tsc -d -m es2015 && mv ./index.js ./index.es2015.js && tsc -m commonjs -t es5


> ngcomponent@3.0.1 clean /home/tlv/dev/ngcomponent
> rm -f index.d.ts

test.ts(326,13): error TS2554: Expected 1 arguments, but got 0.
```

### PR DESCRIPTION
**Pull request by tlvince**

### CODE REVIEW

**Comment by bcherny** [comment]
Looks great @tlvince. In the future, please don't increment the version yourself. Thanks!

**Comment by tlvince** [comment]
Apologies. Could you publish that?

**Comment by bcherny** [comment]
Am away from my machine - in the meantime, you can do https://docs.npmjs.com/cli/link.

**Comment by bcherny** [comment]
`+ ngcomponent@3.0.2`

**Pull request merged**
